# Generated by Django 4.0.3 on 2022-06-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cont', models.TextField()),
                ('bip', models.GenericIPAddressField()),
                ('bdate', models.DateTimeField()),
                ('readcnt', models.IntegerField()),
                ('gnum', models.IntegerField()),
                ('onum', models.IntegerField()),
                ('nested', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
